language: python
os: linux
cache: pip
# dist: xenial

matrix:
  include:
    - name: "Python 3.4 on Linux with minimal dependencies"
      python: 3.4
      env: TOXENV=py
      env: MINIMAL=true
    - name: "Python 3.5 on Linux with minimal dependencies"
      python: 3.5
      env: TOXENV=py
      env: MINIMAL=true
    - name: "Python 3.6 on Linux"
      python: 3.6
      env: TOXENV=py
      env: MINIMAL=false
    - name: "Python 3.7 on Linux"
      python: 3.7
      env: TOXENV=py
      env: MINIMAL=false
    - name: "Python 3.8 on Linux with minimal dependencies"
      dist: xenial
      python: 3.8
      env: MINIMAL=true
      env: TOXENV=py
    - name: "Python 3.8 on Linux"
      dist: xenial
      python: 3.8
      env: TOXENV=py
      env: MINIMAL=false
      after_success: codecov  # use this version for the tests!
    - name: "Python 3.9 on Linux with minimal dependencies"
      dist: xenial
      python: 3.9-dev
      env: TOXENV=py
      env: MINIMAL=true
    - name: "Python 3.9 on Linux"
      dist: xenial
      python: 3.9-dev
      env: TOXENV=py
      env: MINIMAL=false
    - name: "Python Nightly on Linux with minimal dependencies"
      dist: bionic
      python: nightly
      env: TOXENV=py
      env: MINIMAL=true
    - name: "Python Nightly on Linux"
      dist: bionic
      python: nightly
      env: TOXENV=py39
      env: MINIMAL=false
    - name: "Pypy 3 on Linux with minimal dependencies"
      python: pypy3
      env: MINIMAL=true
      env: TOXENV=pypy3
    - name: "Pypy 3 on Linux"
      python: pypy3
      env: MINIMAL=false
      env: TOXENV=pypy3
    - name: "Python 3 on older macOS with minimal dependencies"
      os: osx
      osx_image: xcode9.4
      language: shell
      env: MINIMAL=true
      before_install:
        - sw_vers
        - python3 --version
        - pip3 --version
    - name: "Python 3 on macOS with minimal dependencies"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: MINIMAL=true
      before_install:
        - sw_vers
        - python3 --version
        - pip3 --version
    - name: "Python 3 on recent macOS"
      os: osx
      osx_image: xcode12.2
      language: shell
      env: MINIMAL=false
      before_install:
        - sw_vers
        - python3 --version
        - pip3 --version
    - name: "Python 3 on Windows with minimal dependencies"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      env: MINIMAL=true
    - name: "Python 3 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      env: MINIMAL=false
  allow_failures:
    - python: nightly
    - python: pypy3
    - os: windows
  fast_finish: true


install:
  - pip3 install -U pip
  - pip3 install -U pytest pytest-cov codecov tox
  - if $MINIMAL; then pip3 install -U .;
    else pip3 install -U ".[all]"; fi

script:
  - tox
  # - pytest tests/unit_tests.py --cov=codecov

notifications:
  email:
    on_success: never
    on_failure: change
