sudo: false
language: python

matrix:
  include:
    - name: "Python 3.4 on Linux"
      os: linux
      python: 3.4
      env: TOXENV=py34
    - name: "Python 3.4 on OS X"
      os: osx
      python: 3.4
      env: TOXENV=py34
    - name: "Python 3.5 on Linux"
      os: linux
      python: 3.5
      env: TOXENV=py35
    - name: "Python 3.5 on OS X"
      os: osx
      python: 3.5
      env: TOXENV=py35
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
      env: TOXENV=py36
    - name: "Python 3.6 on OS X"
      os: osx
      python: 3.6
      env: TOXENV=py36
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
      env: TOXENV=py37
    - name: "Python 3.7 on OS X"
      os: osx
      python: 3.7
      env: TOXENV=py37
    - name: "Python 3.8 on Linux Xenial"
      os: linux
      dist: xenial
      python: "3.8-dev"
      env: TOXENV=py38
  allow_failures:
    - python: "3.8-dev"
      env: TOXENV=py38
  # fast_finish: true

before_install:
  - pip install codecov tox

install:
  - pip install .

script:
  - tox
  # - pytest
  # - coverage run --source trafilatura tests/unit_tests.py

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change

#cache:
#  pip: true

# os:
#  - windows # not supported
